baseURL = "https://NoNeaux.github.io/Portfolio/"
languageCode = "en-us"
title = "My Resume"
theme = "book"

# Disable search
[params]
  [params.search]
    enable = false

# Optional: simplify site (no taxonomy pages, etc.)
disableKinds = ["taxonomy", "taxonomyTerm", "section", "RSS", "sitemap", "page"]
